---
version: '3'
services:
  jenkins:
    image: arsharaf/myjenkins:2.387.3
    container_name: jenkins
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - "jenkins-data:/var/jenkins_home"
      - "jenkins-docker-certs:/certs/client:ro"
    networks:
      - homelab
    restart: on-failure
volumes:
  jenkins-data:
    name: jenkins-data
  jenkins-docker-certs:
    name: jenkins-docker-certs
networks:
  homelab:
    external: true
...




