---
version: '3.8'
services:
  jenkins:
    build:
      dockerfile: jenkins_Dockerfile
    container_name: jenkins
    ports:
      - '8080:8080'
      - '5000:5000'
    volumes:
      - "jenkins-data:/var/jenkins_home"
      - "jenkins-docker-certs:/certs/client:ro"
    networks:
      - homelab
    restart: on-failure
    depends_on:
      - jenkins_bind

  jenkins_bind:
    container_name: bind_jenkins
    build:
      dockerfile: jenkins_bind_dockerfile
    privileged: true
    restart: on-failure
    volumes:
      - "jenkins-docker-certs:/certs/client"
      - "jenkins-data:/var/jenkins_home"
    ports:
      - "2376:2376"
    networks:
      homelab:
        aliases:
          - "docker"
          
volumes:
  jenkins-data:
    name: jenkins-data
  jenkins-docker-certs:
    name: jenkins-docker-certs
networks:
  homelab:
    external: true
...




